#
# justmake
#
# by exa aka Eray Ozkural 2001
# see COPYING file that comes with this distribution

PACKAGE = cxx_skel
VERSION = 0.0.1
BUILDARCH = i686
# valid build configs : dbg, opt, optdbg
BUILD = dbg

include justmake/Makefile.justmake
