# Makefile
#
# by exa aka Eray Ozkural 2001
# see COPYING file that comes with this distribution

# Include automatic dependencies

CXXDEPS=$(addprefix $(workingdir)/,$(CXXFILES:.cxx=.d))
CCDEPS=$(addprefix $(workingdir)/,$(CCFILES:.cc=.d))
CDEPS=$(addprefix $(workingdir)/,$(CFILES:.c=.d))

DEPENDENCIES=$(CXXDEPS) $(CCDEPS) $(CDEPS)

ifndef NO_AUTODEPENDENCY

# make-dir := $(shell echo shtool mkdir $(1))

make-dir := $(shell echo ciyak)

ifneq ($(DEPENDENCIES),)
# $(call map,make-dir,$(dir $(DEPENDENCIES)))
# $(shell echo zort)
include $(DEPENDENCIES)
endif

endif
